### ISSUE TITLE
ModuleNotFoundError: No module named 'fbchat'

### ISSUE THREAD

**Issue by hellobrother222** [MS-Jahan/Messenger-Message-Logger#1]
`C:\Users\Ismael> cd C:\Users\Ismael\Downloads\Messenger-Message-Logger-master\Messenger-Message-Logger-master

C:\Users\Ismael\Downloads\Messenger-Message-Logger-master\Messenger-Message-Logger-master> python3 main.py
Traceback (most recent call last):
  File "C:\Users\Ismael\Downloads\Messenger-Message-Logger-master\Messenger-Message-Logger-master\main.py", line 6, in <module>
    from fbchat import Client
ModuleNotFoundError: No module named 'fbchat'`

Getting this error when trying to run main.py.

I've tried installing fbchat from its repo, but I still get this error

**Comment by MS-Jahan** [comment]
Have you done `pip install fbchat`?
Are you using python2 and python3 both in your machine? If so, you may have installed fbchat in python2 rather than python3 or vice versa.

If that doesn't work, try downloading [this whl file](https://github.com/fbchat-dev/fbchat/releases/download/v1.9.7/fbchat-1.9.7-py2.py3-none-any.whl) and install with pip: `pip install path/to/whl/file`

**Comment by DARKgod2** [comment]
hello mr jahan may i contact u on telegram? we have chatted before but i lost your name

**Comment by MS-Jahan** [comment]
[Here](https://t.me/sa61t)
